### ISSUE TITLE
viralliset tekstit

### ISSUE THREAD

**Issue by ptman** [matrix-ax/documentation#1]
- mitä henkilötietoja (tosi vähän, mailiosoite ja jotain ip:itä lokiin)
- miten käsitellään 
- lain vaatimat sepustukset

**Comment by olmari** [comment]
Tein tuossa joksus tietosuojaselosteelle mallipohjan https://github.com/matrix-ax/documentation/blob/main/Tietosuojaseloste%20malli.md

**Comment by uumas** [comment]
Olisko jonkulainen ylläpitositoumus tätä samaa settiä?
