### ISSUE TITLE
Keyclockin tutkiminen

### ISSUE THREAD

**Issue by samip5** [matrix-ax/documentation#11]
Selvittää onnistuuko meidän vaatimukset Keyclockin avulla.

- Sähköposti whitelist & matching

**Comment by olmari** [comment]
K.I.S.S. ensin, ja jatkoksi sitten myöhemmin tutkia SMS authia jos email (domain-)whitelist ei osu kohdalle, rel: https://github.com/spiashko/keycloak-sms-authenticator

**Comment by samip5** [comment]
Pitäisi onnistua sillä, mutta omaa osaamista Keyclockin käyttöön ei ole, joten Authentik it is.
