### ISSUE TITLE
Suomalaiset sähköposti-verkkotunnukset

### ISSUE THREAD

**Issue by samip5** [matrix-ax/documentation#12]
### Kaupungit
hel.fi
vaasa.fi
tampere.fi
*.ouka.fi
turku.fi

### Peruskoulut
kotka.opit.fi
edu.turku.fi
eduouka.fi

### Yliopistot ja ammattikorkeakoulut
helsinki.fi
*.oulu.fi
*.turkuamk.fi
jyu.fi
jamk.fi
tuni.fi
*.utu.fi
ekami.fi 
edu.ekami.fi
aalto.fi
paivola.fi (mihinköhän kategoriaan kuuluu?)

### Operaattorit
*.inet.fi
kolumbus.fi
elisanet.fi
saunalahti.fi
netti.fi
nic.fi
netikka.fi
sci.fi
anvianet.fi
kymp.net
jippii.fi
kotinet.com
eunet.fi
welho.com

### Yhdistykset
kapsi.fi
hacklab.fi
nullroute.fi
fixme.fi
far.fi

### Yritykset
assembly.org

### Viranomaiset
eduskunta.fi
gov.fi
supo.fi
poliisi.fi

**Comment by vurpo** [comment]
utu.fi

**Comment by tulir** [comment]
https://github.com/JetBrains/swot/tree/master/lib/domains/fi saattaa olla hyödyllinen (lista oppilaitosten .fi sähköpostidomaineista)

**Comment by SamiLehtinen** [comment]
mailsuomi.com puuttuu selvästi, vaikka ei .fi domain ole.

**Comment by ptman** [comment]
*.fi?

iki.fi
far.fi
fixme.fi
assembly.org
meiliboxi.fi
aalto.fi
hut.fi
luukku.com
paivola.fi

**Comment by uumas** [comment]
Ei haluta semmosia mihin on avoin rekisteröityminen (kuten luukku.com tai *.fi)

**Comment by samip5** [comment]
Halutaankohan meiliboxia listalle?

**Comment by uumas** [comment]
meiliboxi näyttää avoimelta joo eli ei haluta

**Comment by samip5** [comment]
Entäs iki.fi? Se on yhdistys kyllä, ja tarvii olla yhdistyksen jäsen ainakin. :thinking:

**Comment by uumas** [comment]
Mun mielestä iki voidaan pitää selkeenä. Tavoite on kai rajata niin et pitäis olla jotain yhteyksiä Suomeen ja ainaki mun mielestä se, et on maksanu suomalaiselle yhdistykselle 40€ jäsenmaksun on aivan riittävä.

`whois hut.fi` osaa kertoa et aalto-yliopisto ja wikipedia kertoo et helsinki university of technology joka yhdistyi aaltoon 2010. Eli en tiiä onko noita sähköposteja jollain vielä jäljellä...

**Comment by ptman** [comment]
Ajattelin että siellä hut:lla on niitä jääriä jotka pitää vanhaa osoitetta hengissä. Mutta kai niillä tosiaan on aalto.fi -osoitekin käytössä.

**Comment by ptman** [comment]
Eiköhän tämän voisi sulkea. Lista on käytössä ja muutokset omina tiketteinään. Avatkaa takaisin jos eri mieltä.
