### ISSUE TITLE
palvelimet pystyyn

### ISSUE THREAD

**Issue by ptman** [matrix-ax/documentation#3]
1. possu
2. synapse
3. erilliset mediadatat?

**Comment by vranki** [comment]
Media repo vois olla oma pannunsa. Possu ja synapse samaan koska ovat vahvasti sidoksissa toisiinsa.

**Comment by jhulkko** [comment]
> Media repo vois olla oma pannunsa. Possu ja synapse samaan koska ovat vahvasti sidoksissa toisiinsa.

Mediareposta oli spekulaatiota, että olisiko hyvä pystyttää Kapsin kanssa yhteinen? Muutoinhan sama sisältö käytännössä duplikoituu samassa infrassa. Tästä voisi avata erillisen tiketin ja keskustelun koska puuha vaatii koordinointia ja suunnittelua Kapsin kanssa.

PostgreSQL kannattaa laittaa omalle VM:lle koska se on silloin skaalattavissa ja kuorman ym kannalta monitoroitavissa sekä säädettävissä omana kokonaisuutenaan. Lisäksi mikäli palvelu kasvaa, niin eriytettynä selvittäneen hieman pidemmälle ennen tarvetta hajauttaa palvelua useammalle VM:lle. Synapse tulee jossain vaiheessa tarpeelliseksi hajauttaa joka tapauksessa useammalle VM:lle mikäli käyttäjämäärä kasvaa riittävän suureksi. En tekisi tässä vaiheessa teknistä velkaa, vaan pyrkisin jo lähtökohtaisesti hyvän kokonaisarkkitehtuurin suuntaan tässä.

**Comment by vranki** [comment]
Ok, koska ei ole faktaa siitä miten vaikutaa possun ja synapsen ajo samalla vs eri koneella niin arkkitehtuurin kannalta lienee fiksuin tosiaan erillinen VM.

Onko varmistettu että mediarepon voi jakaa usean kotipalvelimen kesken?

**Comment by olmari** [comment]
Sehän on koko [matrix-media-repo](https://github.com/turt2live/matrix-media-repo)n fundamentaalisia ideoita että useampi kotipalvelin jakaa saman media repon :)

**Comment by vranki** [comment]
Uumas tekee tunnarit, antakaa ssh public keyt loginia varten. Jassu tekee ylläpitosopparin.

**Comment by jhulkko** [comment]
Asennettu: screen, git, etckeeper

**Comment by samip5** [comment]
Eikös tämän voisi laittaa tehdyksi?

**Comment by uumas** [comment]
joo
