### ISSUE TITLE
https://www.pikaviestin.fi/ käyttää fonts.googleapis.com:ia - huono yksityisyyden kannalta

### ISSUE THREAD

**Issue by hsuutari** [matrix-ax/documentation#31]
Webbisivulla käytössä etäfontit Googlelta. He oletettavasti eivät tarjoa fontteja hyvyyttään, vaan saadakseen kerättyä tietoja sivustojen käyttäjistä. Tämä on mielestäni Pikaviestimen yleisestä hengestä poikkeava piirre, joka pitäisi muuttaa.

(Itse toki suodatan ko. fontit pois, mutta suurin osa käyttäjistä varmaan ei.)

**Comment by samip5** [comment]
PR:iä otetaan vastaan. :)
