### ISSUE TITLE
**Website**

### ISSUE THREAD

**Issue by ptman** [matrix-ax/documentation#5]
Kielenä Suomi. Keep it simple, stupid.

We need:
- [x] Simple AF layout
- [x] Tietosuojaseloste
- [ ] Rekisteriseloste (GDPR compliant)
- [ ] Käyttöehdot
- [ ] Code of Conduct / Netiketti
- [ ] Ohjeet suomeksi

**Comment by uumas** [comment]
GitHub pages ois helppo, oma staattisten sivujen generaattori myös vaihtoehto. WordPressiä ei varmaan haluta.

**Comment by ptman** [comment]
noni, sehän on pystyssä
