### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by ptman** [matrix-ax/documentation#6]
I have both matrix.ax and pikaviestin.fi that can be used for this. I can hand them over once we have this up and running and some legal entity to hand them to.

**Comment by vranki** [comment]
There was discussion about domains and looks like pikaviestin.fi is the favourite. Matrix.ax is (IMO) not good as it's not based on finnsih word, is difficult to pronounce and sounds unfriendly. Better alternatives welcome.

**Comment by vranki** [comment]
sauna.chat and viesti.chat also suggested.

**Comment by vranki** [comment]
voting started, check our matrix room for link

**Comment by vranki** [comment]
Vote results:

1. pikaviestin.fi
2. sauna.chat & matrix.ax

**Comment by samip5** [comment]
Pikaviestin.fi appears to still serve the Kapsi default no configuration vhost.

**Comment by olmari** [comment]
Pikaviestin.fi it is then.
