### ISSUE TITLE
SMTP/sähköpostipalvelin

### ISSUE THREAD

**Issue by larikuistio** [matrix-ax/documentation#7]
Tarjoaako kapsi vai laitetaanko oma? Tarvii ainakin password recovery maileja varten.

**Comment by uumas** [comment]
Kapsi voi varmasti tarjota (ellei jollain oo hinkua konffia omaa mailipannua)

**Comment by olmari** [comment]
SFP, DKIM, DMARC-tiedot ja tietueet kohdilleen myös niin tulee hyvä, tietueita kykenen kyllä pohtimaan pureskelluksi, DNS:ään minulla ei taida olla virtaa :)

**Comment by samip5** [comment]
SPF, DKIM yms kun puuttuu niin esim Office 365 laittaa postit spämmiin.
